Show contract method names
near/near-cli-rs pull request #92
Opened 2022-03-15 14:20 UTC by Buckram123

Creating extension for #70

2022-03-15 22:36 UTC, frol commented
@Buckram123 

1. I recommend using `interactive-clap` to build the extensions with interactivity (see #93)
2. We should not merge extensions into this repo, instead:
  2.1. setup a separate repo
  2.2. configure CI (copy `.github/workflows`)
  2.3. add the reference and a short description to near-cli-rs README

2022-03-15 22:37 UTC, frol requested changes

2022-03-15 22:37 UTC, frol commented on extensions/method-names/Cargo.toml
> +name = "method-names"
It should be `near-cli-method-names` to produce a binary that `near-cli-rs` can pick up when one calls `near-cli method-names`.

2022-03-22 13:54 UTC, Buckram123 commented
Building it [here](https://github.com/Buckram123/near-cli-method-names), working on:

- [ ] README
- [ ] Configure CI

2022-10-22 09:54 UTC, frol commented
@Buckram123 Ouch, I somehow missed your last message. Since that time devtools team developed [NEAR ABI](https://github.com/near/abi) and [`cargo near` extension](https://github.com/near/cargo-near).

I feel `cargo near` should remain dedicated to NEAR development on Rust, so we can start thinking about `near-cli-dev` which would be a generic extension for developers and yet agnostic to the language. It will include this feature with ABI support (using it to not only list the functions but also their signatures), and [more](https://github.com/near/near-cli-rs/blob/master/docs/NEW_NEAR_CLI_INTERFACE.md#developer-extension) (the commands layout still needs to be properly designed).

2024-03-06 08:10 UTC, frol commented
This is now implemented as `near contract inspect` command in #293

2024-03-06 08:10 UTC, closed without merging